"""
Django settings for human_challenge project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured


env = environ.Env(
    DEBUG_MODE=(bool, False),
    ALLOW_HOSTS=(list, []),
    CSRF_TRUSTED_HOSTS=(list, []),
    HCAPTCHA_SITEKEY=(str, "10000000-ffff-ffff-ffff-000000000001"),
    HCAPTCHA_SECRETKEY=(str, "0x0000000000000000000000000000000000000000"),
    JWT_PRIVATE_KEY_PATH=(str, ),
    JWT_PUBLIC_KEY_PATH=(str, ),
    ISSUESER=(str, 'example.com'),
    EXPIRING_IN=(int, 300),
    JWT_KID=(str, "v1"),
)

DEBUG = env('DEBUG_MODE')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
if DEBUG:
    BASE_DIR = Path(__file__).resolve().parent.parent
else:
    BASE_DIR = Path('/data/')

environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = env.list('ALLOW_HOSTS')

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_HOSTS')

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'human_challenge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'human_challenge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env('REDIS_HOST'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": env('REDIS_PASSWORD'),
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

HCAPTCHA_SITEKEY = env('HCAPTCHA_SITEKEY')
HCAPTCHA_SECRETKEY = env('HCAPTCHA_SECRETKEY')

PRIVATE_KEY_PATH = env.str('JWT_PRIVATE_KEY_PATH')
PUBLIC_KEY_PATH = env.str('JWT_PUBLIC_KEY_PATH')

if not (PRIVATE_KEY_PATH and PUBLIC_KEY_PATH):
    raise ImproperlyConfigured

_PRIV = open(BASE_DIR / PRIVATE_KEY_PATH)
_PUB = open(BASE_DIR / PUBLIC_KEY_PATH)

JWT_PRIVATE_KEY = _PRIV.read()
JWT_PUBLIC_KEY = _PUB.read()

_PRIV.close()
_PUB.close()

JWT_ALGORITHM = "ES256"

JWT_ISSUESER = env('ISSUESER')

JWT_EXPIRING_IN = env.int('EXPIRING_IN')

JWT_KID = env("KID")